-- Run this script in the Supabase SQL Editor for the app's project.

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  current_height_cm numeric not null check (current_height_cm > 0),
  age_years integer not null check (age_years > 0),
  gender text not null check (gender in ('male', 'female', 'other')),
  mother_height_cm numeric check (mother_height_cm > 0),
  father_height_cm numeric check (father_height_cm > 0),
  ethnicity text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists mother_height_cm numeric check (mother_height_cm > 0),
  add column if not exists father_height_cm numeric check (father_height_cm > 0);

create table if not exists public.height_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  cm numeric not null check (cm > 0),
  logged_at timestamptz not null default now()
);

create index if not exists height_logs_user_logged_at_idx
  on public.height_logs (user_id, logged_at);

alter table public.profiles enable row level security;
alter table public.height_logs enable row level security;

grant select, insert, update on public.profiles to authenticated;
grant select, insert, delete on public.height_logs to authenticated;

drop policy if exists "Users can read their own profile" on public.profiles;
create policy "Users can read their own profile"
  on public.profiles for select
  to authenticated
  using ((select auth.uid()) = id);

drop policy if exists "Users can create their own profile" on public.profiles;
create policy "Users can create their own profile"
  on public.profiles for insert
  to authenticated
  with check ((select auth.uid()) = id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
  on public.profiles for update
  to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

drop policy if exists "Users can read their own height logs" on public.height_logs;
create policy "Users can read their own height logs"
  on public.height_logs for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can create their own height logs" on public.height_logs;
create policy "Users can create their own height logs"
  on public.height_logs for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their own height logs" on public.height_logs;
create policy "Users can delete their own height logs"
  on public.height_logs for delete
  to authenticated
  using ((select auth.uid()) = user_id);

create or replace function public.create_profile_for_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.raw_user_meta_data ? 'current_height_cm'
     and new.raw_user_meta_data ? 'age_years'
     and new.raw_user_meta_data ? 'gender' then
    insert into public.profiles (
      id,
      current_height_cm,
      age_years,
      gender,
      mother_height_cm,
      father_height_cm,
      ethnicity
    )
    values (
      new.id,
      (new.raw_user_meta_data ->> 'current_height_cm')::numeric,
      (new.raw_user_meta_data ->> 'age_years')::integer,
      new.raw_user_meta_data ->> 'gender',
      nullif(new.raw_user_meta_data ->> 'mother_height_cm', '')::numeric,
      nullif(new.raw_user_meta_data ->> 'father_height_cm', '')::numeric,
      nullif(new.raw_user_meta_data ->> 'ethnicity', '')
    );
  end if;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_create_profile on auth.users;
create trigger on_auth_user_created_create_profile
  after insert on auth.users
  for each row execute function public.create_profile_for_new_user();
